# Generated by Django 4.2.15 on 2024-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=255)),
                ("professor", models.CharField(max_length=255)),
                ("credits", models.IntegerField(blank=True, null=True)),
                ("exam_number", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
