# Generated by Django 4.2.15 on 2024-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="assessment",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="outcomes",
            field=models.CharField(default=0.0004940711462450593, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="module",
            name="exam_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
