# Generated by Django 4.2.15 on 2024-09-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_module_assessment_module_outcomes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="exam_number",
        ),
    ]
